// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    course,
    period,
    semester,
    courseClass,
    session,
    student,
    attendance,
    registration,
  ];
  late final Shape0 course = Shape0(
    source: i0.VersionedTable(
      entityName: 'course',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 period = Shape1(
    source: i0.VersionedTable(
      entityName: 'period',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_3, _column_4, _column_5, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 semester = Shape2(
    source: i0.VersionedTable(
      entityName: 'semester',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_8, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 courseClass = Shape3(
    source: i0.VersionedTable(
      entityName: 'course_class',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 session = Shape4(
    source: i0.VersionedTable(
      entityName: 'session',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_8, _column_16, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 student = Shape5(
    source: i0.VersionedTable(
      entityName: 'student',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_18, _column_1, _column_19, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 attendance = Shape6(
    source: i0.VersionedTable(
      entityName: 'attendance',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id, student_id)'],
      columns: [_column_20, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 registration = Shape7(
    source: i0.VersionedTable(
      entityName: 'registration',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(course_class_id, student_id)'],
      columns: [_column_16, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get searchKey =>
      columnsByName['search_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'search_key',
      aliasedName,
      false,
      generatedAs: i1.GeneratedAs(
        const i1.CustomExpression('createSearchKey(name, id)'),
        true,
      ),
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL GENERATED ALWAYS AS (createSearchKey(name, id)) STORED',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startHour =>
      columnsByName['start_hour']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startMinute =>
      columnsByName['start_minute']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endHour =>
      columnsByName['end_hour']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endMinute =>
      columnsByName['end_minute']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_hour',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (start_hour BETWEEN 0 AND 23)',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_minute',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (start_minute BETWEEN 0 AND 59)',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_hour',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (end_hour BETWEEN 0 AND 23)',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_minute',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (end_minute BETWEEN 0 AND 59)',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get classCode =>
      columnsByName['class_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get dayOfWeek =>
      columnsByName['day_of_week']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fromPeriod =>
      columnsByName['from_period']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get toPeriod =>
      columnsByName['to_period']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get semesterId =>
      columnsByName['semester_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'class_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'day_of_week',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'from_period',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES period(id)',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'to_period',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES period(id)',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'course_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES course(id)ON UPDATE CASCADE ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_15(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'semester_id',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL REFERENCES semester(id)ON UPDATE CASCADE ON DELETE RESTRICT',
);

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get courseClassId =>
      columnsByName['course_class_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_16(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'course_class_id',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL REFERENCES course_class(id)ON UPDATE CASCADE ON DELETE CASCADE',
);
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sortKey =>
      columnsByName['sort_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get searchKey =>
      columnsByName['search_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'email',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sort_key',
      aliasedName,
      false,
      generatedAs: i1.GeneratedAs(
        const i1.CustomExpression('getFirstName(name)'),
        true,
      ),
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL GENERATED ALWAYS AS (getFirstName(name)) STORED',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get attendanceStatus =>
      columnsByName['attendance_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get numContributions =>
      columnsByName['num_contributions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'attendance_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'num_contributions',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES session(id)ON UPDATE CASCADE ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'student_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES student(id)ON UPDATE CASCADE ON DELETE CASCADE',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get courseClassId =>
      columnsByName['course_class_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get studentId =>
      columnsByName['student_id']! as i1.GeneratedColumn<String>;
}

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    course,
    period,
    semester,
    courseClass,
    session,
    student,
    attendance,
    registration,
  ];
  late final Shape0 course = Shape0(
    source: i0.VersionedTable(
      entityName: 'course',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 period = Shape1(
    source: i0.VersionedTable(
      entityName: 'period',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_3, _column_4, _column_5, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 semester = Shape2(
    source: i0.VersionedTable(
      entityName: 'semester',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_8, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 courseClass = Shape3(
    source: i0.VersionedTable(
      entityName: 'course_class',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 session = Shape8(
    source: i0.VersionedTable(
      entityName: 'session',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_8, _column_16, _column_17, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 student = Shape5(
    source: i0.VersionedTable(
      entityName: 'student',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_18, _column_1, _column_19, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 attendance = Shape6(
    source: i0.VersionedTable(
      entityName: 'attendance',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id, student_id)'],
      columns: [_column_20, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 registration = Shape7(
    source: i0.VersionedTable(
      entityName: 'registration',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(course_class_id, student_id)'],
      columns: [_column_16, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get courseClassId =>
      columnsByName['course_class_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ignoreAttendance =>
      columnsByName['ignore_attendance']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ignore_attendance',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (ignore_attendance IN (0, 1))',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
